### ISSUE TITLE
期望能够编译ARM64架构的镜像

### ISSUE THREAD

**Issue by vantis-zh** [MistEO/Pallas-Bot#93]
通过docker-compose方式进行搭建时候发现没有该架构镜像。
本地编译报错，因为部分依赖的包没有这个架构的编译包。

**Comment by vantis-zh** [comment]
看起来只是 fastapi 没有对应arm64的版本
我切换了个 bmltenabled/uvicorn-gunicorn-fastapi:python3.9-slim 还在本地编译中

**Comment by Tunglies** [comment]
> 看起来只是 fastapi 没有对应arm64的版本 我切换了个 bmltenabled/uvicorn-gunicorn-fastapi:python3.9-slim 还在本地编译中

解决了吗？

**Comment by vantis-zh** [comment]
> > 看起来只是 fastapi 没有对应arm64的版本 我切换了个 bmltenabled/uvicorn-gunicorn-fastapi:python3.9-slim 还在本地编译中
> 
> 解决了吗？

没有
本地启动报
[INFO  wait] Host [mongodb:27017] not yet available...

网络配置我切过好几次了orz

```
version: "3"

services:
  pallasbot:
    container_name: pallasbot
    image: vantis/pallas-bot
    restart: always
    ports:
      - "5140:8080"
    env_file:
      - ".env.prod"
    links:
      - "mongodb:mongodb"
      - "qsign:qsign"
    networks:
      - pallas_default
    environment:
      TZ: Asia/Shanghai
      ENVIRONMENT: prod
      APP_MODULE: bot:app
      MAX_WORKERS: 1
      WAIT_HOSTS: mongodb:27017
    volumes:
      - /home/ubuntu/pallas/resource/:/app/resource
      - /home/ubuntu/pallas/accounts/:/app/accounts
      - /home/ubuntu/pallas/.env.prod:/app/.env.prod
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:4.4.19-focal
    restart: always
    networks:
      - pallas_default
    environment:
      TZ: Asia/Shanghai
      wiredTigerCacheSizeGB: 1.5
    volumes:
      - /home/ubuntu/pallas/mongo/data:/data/db
      - /home/ubuntu/pallas/mongo/logs:/var/log/mongodb

  qsign:
    container_name: qsign
    image: xzhouqd/qsign:core-1.1.9
    networks:
      - pallas_default
    environment:
      - PORT=8080
      - COUNT=3
      - ANDROID_ID=114514
    restart: always

networks:
  pallas_default:
    driver: bridge

```
这是我挣扎之后目前在调试的配置
